# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DePoint' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'SDWebImage'
    pod 'YYKit'
    pod 'UITableView+FDTemplateLayoutCell'
    pod 'WMPageController'
    pod 'BlocksKit'
    pod 'CocoaLumberjack'
    pod 'MLTransition'
    pod 'AFNetworking'
    pod 'MBProgressHUD'
    
    pod 'UMengAnalytics-NO-IDFA' #友盟数据统计 无IDFA
    
    #pod 'AMap3DMap' #3D地图SDK
    #pod 'AMap2DMap' #2D地图SDK(2D地图和3D地图不能同时使用)
    pod 'AMapSearch' #搜索服务SDK
end
